In [17]:
import pandas as pd

In [18]:
df = pd.read_excel("movies.csv.xlsx")
df.head()

,MovieID,Title,Genre,Director,LeadActor,Year,Language,Rating
0,M001,Avengers,Action|SciFi,Joss Whedon,Robert Downey Jr,2012,English,8.0
1,M002,Iron Man,Action|SciFi,Jon Favreau,Robert Downey Jr,2008,English,7.9
2,M003,Thor,Action|Fantasy,Kenneth Branagh,Chris Hemsworth,2011,English,7.0
3,M004,Captain America,Action|Adventure,Joe Johnston,Chris Evans,2011,English,6.9
4,M005,Batman Begins,Action|Crime,Christopher Nolan,Christian Bale,2005,English,8.2

In [19]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MovieID    25 non-null     object
 1   Title      25 non-null     object
 2   Genre      25 non-null     object
 3   Director   25 non-null     object
 4   LeadActor  25 non-null     object
 5   Year       25 non-null     int64
 6   Language   25 non-null     object
 7   Rating     25 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.7+ KB

              Year    Rating
count    25.000000  25.00000
mean   2011.600000   7.74000
std       5.686241   0.74162
min    1997.000000   5.40000
25%    2009.000000   7.40000
50%    2012.000000   7.80000
75%    2015.000000   8.10000
max    2022.000000   9.00000

In [20]:
df.isnull().sum()

MovieID      0
Title        0
Genre        0
Director     0
LeadActor    0
Year         0
Language     0
Rating       0
dtype: int64

In [21]:
df['features'] = (
    df['Genre'] + ' ' +
    df['Director'] + ' ' +
    df['LeadActor'] + ' ' +
    df['Language']
)

df.head()

,MovieID,Title,Genre,Director,LeadActor,Year,Language,Rating,features
0,M001,Avengers,Action|SciFi,Joss Whedon,Robert Downey Jr,2012,English,8.0,Action|SciFi Joss Whedon Robert Downey Jr English
1,M002,Iron Man,Action|SciFi,Jon Favreau,Robert Downey Jr,2008,English,7.9,Action|SciFi Jon Favreau Robert Downey Jr English
2,M003,Thor,Action|Fantasy,Kenneth Branagh,Chris Hemsworth,2011,English,7.0,Action|Fantasy Kenneth Branagh Chris Hemsworth...
3,M004,Captain America,Action|Adventure,Joe Johnston,Chris Evans,2011,English,6.9,Action|Adventure Joe Johnston Chris Evans English
4,M005,Batman Begins,Action|Crime,Christopher Nolan,Christian Bale,2005,English,8.2,Action|Crime Christopher Nolan Christian Bale ...

In [22]:
# df[["Title", "combine_features"]].tail()
df['features'] = df['features'].str.replace('|', ' ', regex=False)
df['features'] = df['features'].str.lower()

df[['Title', 'features']].head()

             Title                                           features
0         Avengers  action scifi joss whedon robert downey jr english
1         Iron Man  action scifi jon favreau robert downey jr english
2             Thor  action fantasy kenneth branagh chris hemsworth...
3  Captain America  action adventure joe johnston chris evans english
4    Batman Begins  action crime christopher nolan christian bale ...

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
cv = CountVectorizer()
feature_matrix = cv.fit_transform(df['features'])
similarity = cosine_similarity(feature_matrix)

In [24]:
def recommend(movie_name):
    movie_name = movie_name.lower()

    if movie_name not in df['Title'].str.lower().values:
        print("Movie not found in dataset")
        return
    index = df[df['Title'].str.lower() == movie_name].index[0]
    distances = list(enumerate(similarity[index]))
    movies_list = sorted(distances, key=lambda x: x[1], reverse=True)[1:6]
    print("Movies recommended for:", df.iloc[index]['Title'])
    print("--------------------------------")
    for i in movies_list:
        print(df.iloc[i[0]]['Title'])
movie_name = input("Enter the movie name: ");
recommend(movie_name)

Enter the movie name: avengers
Movies recommended for: Avengers
--------------------------------
Iron Man
Thor
Captain America
Batman Begins
The Dark Knight